apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-initiator
spec:
  containers:
  - name: mysql
    image: ubuntu:latest
    volumeMounts:
    - mountPath: /mnt
      name: iscsivol
      subPath: mysql-data
    command: ["sleep","3600"]	  
  volumes:
  - name: iscsivol
    iscsi:
      targetPortal: 192.168.1.70
      iqn: iqn.2016-04.world.srv:target00
      lun: 0
      fsType: ext4
      readOnly: true
      chapAuthDiscovery: true
      chapAuthSession: true
      secretRef: 
        name: chap-secret
