apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: web-app
    spec:
      restartPolicy: Always
      hostname: app
      containers:	     
      - name: web
        image: maho/web:v1
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /var/www
          name: www-vol
      - name: app
        image: maho/app:v1
        env:
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: root
        resources: {}
        volumeMounts:
        - mountPath: /var/www
          name: www-vol
      initContainers:
      - name: cp-contents
        image: maho/web_contents:v1
        command: ["cp",  "-r", ".", "/var/www"]
        volumeMounts:
        - mountPath: /var/www
          name: www-vol
      - name: chmod 
        image: busybox
        command: ["chmod", "-R", "a+r", "/var/www"]
        volumeMounts:
        - mountPath: /var/www
          name: www-vol
      volumes:
      - name: www-vol
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-np
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
  - protocol: TCP
    port: 80
    nodePort: 31514
