apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-webserver
spec:
  replicas: 6
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      containers:
      - name: nginx-container
        image: nginx:alpine
        ports:
        - containerPort: 80
